### ISSUE TITLE
Dead Link in README.md

### ISSUE THREAD

**Issue by stevebanik** [coinapi/helm-charts#15]
https://github.com/coinapi/helm-charts/blob/main/README.md

link refers to https://docs.coinapi.io/oeml.html#running-on-kubernetes-cluster which is a dead link

**Comment by Jacob273** [comment]
Indeed, URL has to be updated in README.md

Here's the address you're looking for:

https://docs.coinapi.io/ems-api/self-hosted-guide#running-on-kubernetes-cluster
